spring:
  datasource:
    url: jdbc:mysql://43.203.238.26:3306/networker  
    username: root
    password: testdbpw
#   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: yuntyu01
    password: "앱 비밀번호"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  
    mode: html
    #encoding: UTF-8
    #servlet:
    #  content-type: text/html
 